FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Gnutti-25luglio-SE2

Applicazione che ritorna informazioni sui voli in partenza e arrivo

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]
        
        

"swagger": "2.0",
"info": {
    "version": "1.0.0",
    "title": "Airport",
    "description": "",
},
    "host": "",
    "basePath": "/",
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
"paths": {
    "/getFlightInfo": {
          "get": {
            "description": "",
            "operationId": "",
            "produces": [
            "application/json",
            ],
            "parameters": [
                {
                "flighCode"
                }
            ],
        "responses": {
          "200": {
            "description": "flight info",
            "schema": {
              "type": "array",
              "items": {
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
            }
          }
        }
      }
    },
    "/getFlights": {
      "get": {
        "description": "",
        "operationId": "",
        "produces": [
          "application/json",
        ],
        "parameters": [
          {
            "id"
          }
        ],
        "responses": {
          "200": {
            "description": "pet response",
            "schema": {
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
    },
    "/setFlights": {
          "get": {
        "description": "",
        "operationId": "",
        "produces": [
          "application/json",
        ],
        "parameters": [
          {
            "id"
          }
        ],
        "responses": {
          "200": {
            "description": "pet response",
            "schema": {
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
    }
}